import dayjs from "dayjs";

export const bookedDates = [
  { type: "booked", date: dayjs() },
  { type: "booked", date: dayjs().add(1, "day") },
  { type: "booked", date: dayjs().add(2, "day") },
  { type: "booked", date: dayjs().add(3, "day") },
  { type: "booked", date: dayjs().add(4, "day") },
  { type: "booked", date: dayjs().add(5, "day") },
  { type: "booked", date: dayjs().add(6, "day") },
  { type: "booked", date: dayjs().add(7, "day") },
  { type: "booked", date: dayjs().add(8, "day") },
  { type: "booked", date: dayjs().add(9, "day") },
  { type: "booked", date: dayjs().add(10, "day") },
  { type: "booked", date: dayjs().add(11, "day") },
  { type: "booked", date: dayjs().add(12, "day") },
  { type: "booked", date: dayjs().add(13, "day") },
  { type: "booked", date: dayjs().add(14, "day") },
  { type: "booked", date: dayjs().add(15, "day") },
  { type: "booked", date: dayjs().add(16, "day") },
  { type: "booked", date: dayjs().add(17, "day") },
  { type: "booked", date: dayjs().add(18, "day") },
  { type: "booked", date: dayjs().add(19, "day") },

  { type: "pending", date: dayjs().add(40, "day") },
  { type: "pending", date: dayjs().add(41, "day") },
  { type: "pending", date: dayjs().add(42, "day") },
  { type: "pending", date: dayjs().add(43, "day") },
  { type: "pending", date: dayjs().add(44, "day") },
  { type: "pending", date: dayjs().add(45, "day") },
  { type: "pending", date: dayjs().add(46, "day") },
  { type: "pending", date: dayjs().add(47, "day") },
  { type: "pending", date: dayjs().add(48, "day") },
  { type: "pending", date: dayjs().add(49, "day") },
  { type: "pending", date: dayjs().add(50, "day") },
  { type: "pending", date: dayjs().add(51, "day") },
  { type: "pending", date: dayjs().add(52, "day") },
  { type: "pending", date: dayjs().add(53, "day") },
  { type: "pending", date: dayjs().add(54, "day") },
  { type: "pending", date: dayjs().add(54, "day") },
  { type: "pending", date: dayjs().add(56, "day") },
  { type: "pending", date: dayjs().add(57, "day") },
  { type: "pending", date: dayjs().add(58, "day") },
  { type: "pending", date: dayjs().add(59, "day") },
  { type: "pending", date: dayjs().add(60, "day") },
];

